

' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.

Imports System.Reflection


<Assembly: AssemblyVersion("2026.02.26.1723")>
<Assembly: AssemblyFileVersion("2026.02.26.1723")>
<Assembly: AssemblyCopyright("Copyright © S.A.I.E.E. 2026")> 